version: 2

# Configuration de build
build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    post_create_environment:
      # Installation des dépendances pour Sphinx uniquement
      - pip install sphinx==8.2.3 alabaster==1.0.0
    post_install:
      # Pas besoin d'installer Django et autres dépendances pour la doc
      - echo "Documentation build ready"

# Configuration Sphinx
sphinx:
  configuration: source/conf.py
  builder: html
  fail_on_warning: false

# Formats de sortie à générer
formats:
  - pdf
  - epub

# Configuration Python
python:
  install:
    - requirements: docs-require