name: CI/CD Workflow
on:
  push:
    branches:
    - 'master'
env:
  my_token: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set commit hash
        run: echo "COMMIT_HASH=$(git log -1 --format=%h)" >> $GITHUB_ENV
      
      - name: Build Docker image
        run: |
          docker build -t python-lettings:$COMMIT_HASH --build-arg GIT_COMMIT=$COMMIT_HASH .
          echo "Build successful"
      
      - name: Run tests in Docker container
        run: |
          docker run --rm python-lettings:$COMMIT_HASH python -m pytest --cov=.
          echo "Tests passed"
      
      - name: Push to registry
        if: github.event_name != 'pull_request'
        run: |
          echo ${{ secrets.DOCKER_PASSWD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag python-lettings:$COMMIT_HASH leojackson999/python-lettings:$COMMIT_HASH
          docker push leojackson999/python-lettings:$COMMIT_HASH
  
  deploy-to-render:
    needs: build-and-test  # Ce job s'exécute seulement si build-and-test réussit
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json"